name: Deploy Frontend to Amplify

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Amplify Webhook
        run: curl -X POST -d "{}" "$AMPLIFY_WEBHOOK_URL"
        env:
          AMPLIFOY_WEBHOOK_URL: ${{ secrets.AMPLIFY_WEBHOOK_URL }}